#!/usr/node/bin/node

/*
 * vmcfg is a light zonecfg(1M) like command
 * which allows to create the json file
 * used by `vmadm create`.
 */

var fs = require('fs');
var readline = require('readline');

/*
 * Brand Options is not exported by Joyent's VM module
 * So we copy it here - maintaining it is fun.
 * That sucks, but I don't expect this to change a lot.
 */
var joyent_allowed = {
     'add_nics': ['update'],
     'alias': ['create', 'receive', 'update'],
     'autoboot': ['create', 'receive', 'update'],
     'billing_id': ['create', 'receive', 'update'],
     'brand': ['create', 'receive'],
     'cpu_cap': ['create', 'receive', 'update'],
     'cpu_shares': ['create', 'receive', 'update'],
     'create_only': ['receive'],
     'create_timestamp': ['receive'],
     'customer_metadata': ['create', 'receive'],
     'dataset_uuid': ['create', 'receive'],
     'delegate_dataset': ['create', 'receive'],
     'do_not_inventory': ['create', 'receive', 'update'],
     'dns_domain': ['create', 'receive'],
     'filesystems': ['create', 'receive'],
     'filesystems.*.type': ['add'],
     'filesystems.*.source': ['add'],
     'filesystems.*.target': ['add'],
     'filesystems.*.raw': ['add'],
     'filesystems.*.options': ['add'],
     'fs_allowed': ['create', 'receive', 'update'],
     'hostname': ['create', 'receive', 'update'],
     'image_uuid': ['create', 'receive'],
     'internal_metadata': ['create', 'receive'],
     'limit_priv': ['create', 'receive', 'update'],
     'max_locked_memory': ['create', 'receive', 'update'],
     'max_lwps': ['create', 'receive', 'update'],
     'max_physical_memory': ['create', 'receive', 'update'],
     'max_swap': ['create', 'receive', 'update'],
     'nics': ['create', 'receive'],
     'nics.*.allow_dhcp_spoofing': ['add', 'update'],
     'nics.*.allow_ip_spoofing': ['add', 'update'],
     'nics.*.allow_mac_spoofing': ['add', 'update'],
     'nics.*.allow_restricted_traffic': ['add', 'update'],
     'nics.*.blocked_outgoing_ports': ['add', 'update'],
     'nics.*.dhcp_server': ['add', 'update'],
     'nics.*.gateway': ['add', 'update'],
     'nics.*.interface': ['add', 'update'],
     'nics.*.ip': ['add', 'update'],
     'nics.*.mac': ['add', 'update'],
     'nics.*.netmask': ['add', 'update'],
     'nics.*.nic_tag': ['add', 'update'],
     'nics.*.primary': ['add', 'update'],
     'nics.*.vlan_id': ['add', 'update'],
     'nowait': ['create', 'receive'],
     'owner_uuid': ['create', 'receive', 'update'],
     'package_name': ['create', 'receive', 'update'],
     'package_version': ['create', 'receive', 'update'],
     'quota': ['create', 'receive', 'update'],
     'ram': ['create', 'receive', 'update'],
     'remove_customer_metadata': ['update'],
     'remove_internal_metadata': ['update'],
     'remove_nics': ['update'],
     'remove_tags': ['update'],
     'resolvers': ['create', 'receive', 'update'],
     'set_customer_metadata': ['update'],
     'set_internal_metadata': ['update'],
     'set_tags': ['update'],
     'tags': ['create', 'receive'],
     'tmpfs': ['create', 'receive', 'update'],
     'transition': ['receive'],
     'update_nics': ['update'],
     'uuid': ['create', 'receive'],
     'zfs_data_compression': ['create', 'receive', 'update'],
     'zfs_data_recsize': ['create', 'receive', 'update'],
     'zfs_io_priority': ['create', 'receive', 'update'],
     'zfs_root_compression': ['create', 'receive', 'update'],
     'zfs_root_recsize': ['create', 'receive', 'update'],
     'zfs_storage_pool_name': ['create', 'receive'],
     'zonename': ['create', 'receive'],
     'zpool': ['create', 'receive']
 };

var BRAND_OPTIONS = {
    'joyent': {
        'allowed_properties': joyent_allowed,
        'required_properties': {
            'brand': ['create', 'receive'],
            'image_uuid': ['create', 'receive']
        }
    }, 'joyent-minimal': {
        'allowed_properties': joyent_allowed,
        'required_properties': {
            'brand': ['create', 'receive'],
            'image_uuid': ['create', 'receive']
        }
    }, 'kvm': {
        'allowed_properties': {
            'add_disks': ['update'],
            'add_nics': ['update'],
            'alias': ['create', 'receive', 'update'],
            'autoboot': ['create', 'receive', 'update'],
            'billing_id': ['create', 'receive', 'update'],
            'boot': ['create', 'receive', 'update'],
            'brand': ['create', 'receive'],
            'cpu_cap': ['create', 'receive', 'update'],
            'cpu_shares': ['create', 'receive', 'update'],
            'cpu_type': ['create', 'receive', 'update'],
            'create_only': ['receive'],
            'create_timestamp': ['receive'],
            'customer_metadata': ['create', 'receive'],
            'disks': ['create', 'receive'],
            'disks.*.block_size': ['add'],
            'disks.*.boot': ['add', 'update'],
            'disks.*.compression': ['add', 'update'],
            'disks.*.image_name': ['add', 'update'],
            'disks.*.image_size': ['add'],
            'disks.*.image_uuid': ['add'],
            'disks.*.size': ['add'],
            'disks.*.media': ['add', 'update'],
            'disks.*.model': ['add', 'update'],
            'disks.*.nocreate': ['add'],
            'disks.*.path': ['add', 'update'],
            'disks.*.zpool': ['add'],
            'disk_driver': ['create', 'receive', 'update'],
            'do_not_inventory': ['create', 'receive', 'update'],
            'hostname': ['create', 'receive', 'update'],
            'image_uuid': ['create', 'receive'],
            'internal_metadata': ['create', 'receive'],
            'limit_priv': ['create', 'receive', 'update'],
            'max_locked_memory': ['create', 'receive', 'update'],
            'max_lwps': ['create', 'receive', 'update'],
            'max_physical_memory': ['create', 'receive', 'update'],
            'max_swap': ['create', 'receive', 'update'],
            'nics': ['create', 'receive'],
            'nics.*.allow_dhcp_spoofing': ['add', 'update'],
            'nics.*.allow_ip_spoofing': ['add', 'update'],
            'nics.*.allow_mac_spoofing': ['add', 'update'],
            'nics.*.allow_restricted_traffic': ['add', 'update'],
            'nics.*.allow_unfiltered_promisc': ['add', 'update'],
            'nics.*.blocked_outgoing_ports': ['add', 'update'],
            'nics.*.dhcp_server': ['add', 'update'],
            'nics.*.gateway': ['add', 'update'],
            'nics.*.interface': ['add', 'update'],
            'nics.*.ip': ['add', 'update'],
            'nics.*.mac': ['add', 'update'],
            'nics.*.model': ['add'],
            'nics.*.netmask': ['add', 'update'],
            'nics.*.nic_tag': ['add', 'update'],
            'nics.*.primary': ['add', 'update'],
            'nics.*.vlan_id': ['add', 'update'],
            'nic_driver': ['create', 'receive', 'update'],
            'owner_uuid': ['create', 'receive', 'update'],
            'package_name': ['create', 'receive', 'update'],
            'package_version': ['create', 'receive', 'update'],
            'qemu_opts': ['create', 'receive', 'update'],
            'qemu_extra_opts': ['create', 'receive', 'update'],
            'quota': ['create', 'receive', 'update'],
            'ram': ['create', 'receive', 'update'],
            'remove_customer_metadata': ['update'],
            'remove_disks': ['update'],
            'remove_internal_metadata': ['update'],
            'remove_nics': ['update'],
            'remove_tags': ['update'],
            'resolvers': ['create', 'receive', 'update'],
            'set_customer_metadata': ['update'],
            'set_internal_metadata': ['update'],
            'set_tags': ['update'],
            'spice_opts': ['create', 'receive', 'update'],
            'spice_password': ['create', 'receive', 'update'],
            'spice_port': ['create', 'receive', 'update'],
            'transition': ['receive'],
            'update_disks': ['update'],
            'update_nics': ['update'],
            'uuid': ['create', 'receive'],
            'vcpus': ['create', 'receive', 'update'],
            'vga': ['create', 'receive', 'update'],
            'virtio_txburst': ['create', 'receive', 'update'],
            'virtio_txtimer': ['create', 'receive', 'update'],
            'vnc_password': ['create', 'receive', 'update'],
            'vnc_port': ['create', 'receive', 'update'],
            'zfs_io_priority': ['create', 'receive', 'update'],
            'zfs_root_compression': ['create', 'receive', 'update'],
            'zfs_root_recsize': ['create', 'receive', 'update'],
            'zone_dataset_uuid': ['create', 'receive'],
            'zpool': ['create', 'receive']
        }, 'required_properties': {
            'brand': ['create', 'receive']
        }
    }
};

/*
 * End of Joyent's BRAND_OPTIONS object copy
 */

/*
 * validate and write a set prop
 *  - shell.type: main, add
 *  - shell.context: main, disks, nics, filesystems
 *  - prop: Array[0]: property, Array[1]: value
 *  - zonedef: JSON file
 *  - callback: error
 */
//TODO: case were a set prop is a list (e.g. resolvers). Do an add prop ?

var args = process.argv;
if ((args[2] === '-f' || args[2] === '--file')
    && (typeof args[3] !== 'undefined')) {
  filename = args[3];
} else {
  return console.error('Usage: vmcfg -f <filename>');
}

createJson(filename, function (err) {
  if (err)
    console.error(err);
});


function createJson(filename, callback) {

  zonedefFileLoad(filename, function (err, message, json) {
    if (err) {
      callback(err);
    } else {
      if (message) console.log(message);
      zonedefShell(filename, json, function (err) {
        if (err) {
          callback(err);
        } else {
          callback();
        }
      });
    }
  });

}

/*
 * zonedefFileLoad cb:
 *  - error
 *  - message
 *  - file content
 */
function zonedefFileLoad(filename, callback) {
  fs.stat(filename, function (err, stats) {
    if (err) {
      // File doesn't exists
      callback(null, filename + ' does not exists.\nUse \'set brand\' to begin.');
    } else {
      if (stats.isFile()) {
        callback(null, null, fs.readFileSync(filename));
      } else {
        callback('Error: ' + filename + ' is not a file.');
      }
    }
  });
}

function writeSetPropToJSON(shell, prop, zonedef, callback) {

  if (!prop[1]) {
    return callback('Error: No value specified');
  }

  var field = prop[0].replace(/('|"| )/g, '');
  var value = prop[1].replace(/('|"| )/g, '');


  //zone brand first
  if (typeof zonedef.brand === 'undefined' && field !== 'brand') {
    return callback('Error: You must specify a zone brand first');
  }

  if (field === 'brand') {
    if (typeof BRAND_OPTIONS[value] !== 'undefined') {
      zonedef.brand = value;
    }
    else {
      return callback('Error: ' + value + ' is not a correct brand.');
    }
  }

  // nic, disk and fs properties are added with `add`
  if (field.match(/(nics|disks|filesystems)/g)) {
    return callback('You must use add (disk|net|fs) to setup this property');
  }


  //brand is setup we can accept allowed and required properties
  if (shell.type === 'main' && zonedef.brand !== 'undefined') {

    // Allowed/Required and create-able for this brand ?
    if ((BRAND_OPTIONS[zonedef.brand].allowed_properties.hasOwnProperty(field)
          && BRAND_OPTIONS[zonedef.brand].allowed_properties[field].indexOf('create') !== -1)
      ||(BRAND_OPTIONS[zonedef.brand].required_properties.hasOwnProperty(field)
          && BRAND_OPTIONS[zonedef.brand].required_properties[field].indexOf('create') !== -1)) {

      if (field === 'brand' && !BRAND_OPTIONS.hasOwnProperty(value)) {
        return callback('Error: ' + value + ' is not a correct brand.');
      }

      zonedef[field] = value;

    } else {
      return callback('Error: ' + field + ' is not a valide property.');
    }

  } else if (shell.type === 'add') {

    var prefix = shell.context + '.*.'

    //nothing required, only allowed
    if (!BRAND_OPTIONS[zonedef.brand].allowed_properties.hasOwnProperty(prefix+field)) {
      return callback('Error: ' + field + ' is not a valide property.');
    }

    // add property at length - 1
    var i = zonedef[shell.context].length - 1;
    zonedef[shell.context][i][field] = value;

  }

  callback(null);
};

function zonedefShell(filename, json, callback) {

  var zonedef = {};

  if (json) {
    try {
      zonedef = JSON.parse(json);
    } catch (e) {
      return callback('Error: JSON file seems badly formatted');
    }
  }

  /*
   * shell.type is where we are globaly
   * to know what command are allowed
   * - main: add, commit, info, remove, set, quit
   * - add: cancel, end, info, set
   * shell.context is what we add (disks, nics, filesystems)
   */
  var shell = {
    type: 'main',
    context: 'main'
  };

  var rl = readline.createInterface(process.stdin, process.stdout, completer);

  // function for completion - must be a better way than that
  function completer(line) {

    var completions = [];

    completions.push('info');

    if (typeof zonedef.brand === 'undefined') {

      completions.push('verify');
      completions.push('quit');
      completions.push('commit');
      completions.push('set brand=');

    } else if (shell.context === 'main') {

      completions.push('verify');
      completions.push('quit');
      completions.push('commit');
      completions.push('add net');

      if (zonedef.brand === 'kvm') {
         completions.push('add disk');
      } else {
          completions.push('add fs');
      }

      for (var prop in BRAND_OPTIONS[zonedef.brand].required_properties) {
        completions.push('set ' + prop + '=');
      }

      for (var prop in BRAND_OPTIONS[zonedef.brand].allowed_properties) {
        if (!prop.match(/(nics|disks|filesystems)/g)) {
          /*
           * required for image_uuid that is both required and allowed
           * change to: !completions.hasOwnProperty(prop); in the future
           * if more property become mandatory
           */
          if (prop != 'image_uuid')
            completions.push('set ' + prop + '=');
        }
      }

    } else if (shell.type === 'add') {

      completions.push('cancel');
      completions.push('end');

      for (var prop in BRAND_OPTIONS[zonedef.brand].allowed_properties) {
        var reg = new RegExp(shell.context + '\.\*\.');
        if (prop.match(reg)) {
          completions.push('set ' + prop.substr(shell.context.length + 3) + '=');
        }
      }

    }

    var hits = completions.filter(function (c) {
      return !c.indexOf(line);
    });

    return [ hits.length ? hits : completions, line ];

  }
  //end of completer

  var prefix = 'zonedef> ';
  rl.setPrompt(prefix, prefix.length);
  rl.prompt();

  rl.on('line', function (input) {
    var cmd = [];
    cmd[0] = input.trim().split(' ')[0];
    cmd[1] = '';
    for (var i = 1; i < input.trim().split(' ').length; i++) {
      cmd[1] += input.trim().split(' ')[i];
    }

    if (shell.type === 'main') {

      //TODO: Missing zonecfg commands (e.g remove)

      switch (cmd[0]) {

        case 'set':
          var prop = cmd[1].split('=');
          writeSetPropToJSON(shell, prop, zonedef, function (err) {
            if(err) {
              console.error(err);
            }
            rl.prompt();
          });
          break;

        case 'add':
          if (typeof zonedef.brand === 'undefined') {
            console.error('Error: You must specify a zone brand first!');

          } else if(cmd[1] !== 'disk' && cmd[1] !== 'net' && cmd[1] !== 'fs') {
            console.error('Error: ' + cmd[1] + ' is not a valid command.');

          } else {
            shell.type = 'add';
            shell.context = cmd[1];

            if (cmd[1] === 'disk') {
              shell.context = 'disks';
            } else if (cmd[1] === 'net') {
              shell.context = 'nics';
            } else if (cmd[1] === 'fs') {
              shell.context = 'filesystems';
            }


            //Can't add a disk in a zone
            //Can't use fs in a VM
            if (shell.context === 'disks' && zonedef.brand !== 'kvm') {
              shell.type = shell.context = 'main';
              console.error('Error: Adding a disk is only supported on KVM VM. Use add fs instead');
           } else if (shell.context === 'filesystems' && zonedef.brand === 'kvm') {
              shell.type = shell.context = 'main';
              console.error('Error: Filesystems features is not supported on KVM VM. Use add disk instead')
           } else {
              if (typeof zonedef[shell.context] === 'undefined') {
                zonedef[shell.context] = [];
              }

              zonedef[shell.context].push({});

              var prefix = 'zonedef:' + cmd[1] + '> ';
              rl.setPrompt(prefix, prefix.length);
            }
          }
          rl.prompt();

          break;

        case 'verify':
           // Verify does *not* verify type of prop. Only required_properties
          if (typeof zonedef.brand === 'undefined') {
            console.error('Error: Missing property: brand');
          } else {
            for (var prop in BRAND_OPTIONS[zonedef.brand].required_properties) {
              if (typeof zonedef[prop] === 'undefined') {
                console.error('Error: Missing property: ' + prop);
              }
            }
          }
          rl.prompt();
          break;

        case 'commit':
          fs.writeFile(filename, JSON.stringify(zonedef), 'utf-8', function (err) {
            if(err) {
              console.error('Error: ' + err);
            } else {
              console.log('Succesfully written zone definication file ' + filename + '.')
            }
            rl.prompt();
          });
          break;

        case 'info':
          console.log(zonedef);
          rl.prompt();
          break;

        case 'quit':
          rl.question('Warning, quit does not save. Really quit ? [y/N] ', function (a) {
            if (a === 'y' || a === 'Y') {
              rl.close();
              callback();
            } else {
              rl.prompt();
            }
          });
          break;

        case '':
          rl.prompt();
          break;

        default:
          console.error('Error: unknown command ' + cmd[0] + '.');
          rl.prompt();
          break;
      }

    } else if (shell.type === 'add') {

      switch (cmd[0]) {

        case 'cancel':
          zonedef[shell.context].pop();
          if (zonedef[shell.context].length === 0) {
            delete zonedef[shell.context];
          }

        case 'end':
          var prefix = 'zonedef> ';
          rl.setPrompt(prefix, prefix.length);
          rl.prompt();
          shell.type = 'main';
          shell.context = 'main';
          break;

        case 'info':
          var length = zonedef[shell.context].length;
          console.log(zonedef[shell.context][length-1]);
          rl.prompt();
          break;

        case 'set':
          var prop = cmd[1].split('=');
          writeSetPropToJSON(shell, prop, zonedef, function (err) {
            if(err) {
              console.error(err);
            }
            rl.prompt();
          });
          break;

        case '':
          rl.prompt();
          break;

        default:
          console.error('Error: unknown command ' + cmd[0] + '.');
          rl.prompt();
          break;

      }
    }

  });

}
